[package]
name = "soac_opt"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
derive_more = { version = "2", features = ["from"] }
rkyv = { version = "0.8", features = ["alloc"] }
soac_core = { path = "../soac_core" }
soac_ir_blockpy = { path = "../soac_ir_blockpy" }
soac_lowering = { path = "../soac_lowering" }
soac_macros = { path = "../soac_macros" }
tracing = "0.1"
