#!/usr/bin/env python3
"""Generate the SOAC workspace-local crate dependency graph as Graphviz DOT."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
EDGE_KIND_ORDER = {"normal": 0, "build": 1, "dev": 2}


def rel(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def cargo_metadata() -> dict:
    try:
        proc = subprocess.run(
            ["cargo", "metadata", "--no-deps", "--format-version", "1"],
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as err:
        print(f"cargo metadata failed: {err}", file=sys.stderr)
        if isinstance(err, subprocess.CalledProcessError) and err.stderr:
            print(err.stderr, file=sys.stderr)
        raise SystemExit(1) from err
    return json.loads(proc.stdout)


def dot_string(value: str) -> str:
    return json.dumps(value)


def workspace_packages(metadata: dict) -> list[dict]:
    package_by_id = {package["id"]: package for package in metadata["packages"]}
    packages = []
    for package_id in metadata.get("workspace_members", []):
        package = package_by_id.get(package_id)
        if package is None:
            continue
        manifest = Path(package["manifest_path"])
        if rel(manifest).startswith("crates/"):
            packages.append(package)
    return sorted(packages, key=lambda package: package["name"])


def edge_style(kind: str) -> str:
    if kind == "build":
        return 'color="#866118", style=dotted, label="build"'
    if kind == "dev":
        return 'color="#6b7280", style=dashed, label="dev"'
    return 'color="#394150"'


def render_dot(metadata: dict, include_dev: bool) -> str:
    packages = workspace_packages(metadata)
    workspace_names = {package["name"] for package in packages}
    package_by_name = {package["name"]: package for package in packages}
    edges: dict[tuple[str, str], set[str]] = {}

    for package in packages:
        source = package["name"]
        for dep in package.get("dependencies", []):
            target = dep["name"]
            if target not in workspace_names:
                continue
            kind = dep.get("kind") or "normal"
            if kind == "dev" and not include_dev:
                continue
            edges.setdefault((source, target), set()).add(kind)

    lines = [
        "// Generated by .codex/skills/soac-selfdoc/scripts/crate_dependency_graph.py",
        "digraph soac_crate_dependencies {",
        '  graph [rankdir=LR, bgcolor="transparent", pad="0.25", nodesep="0.45", ranksep="0.75"];',
        '  node [shape=box, style="rounded,filled", fillcolor="#f8fafc", color="#475569", fontname="Helvetica", fontsize=11];',
        '  edge [fontname="Helvetica", fontsize=9, arrowsize=0.7];',
        "",
    ]
    for name in sorted(workspace_names):
        package = package_by_name[name]
        lines.append(
            f"  {dot_string(name)} [label={dot_string(name)}, tooltip={dot_string(rel(Path(package['manifest_path']).parent))}];"
        )
    if edges:
        lines.append("")
    for (source, target), kinds in sorted(edges.items()):
        ordered = tuple(sorted(kinds, key=lambda kind: EDGE_KIND_ORDER.get(kind, 99)))
        if len(ordered) == 1:
            attrs = edge_style(ordered[0])
        else:
            label = ", ".join(ordered)
            attrs = f'color="#394150", label={dot_string(label)}'
        lines.append(f"  {dot_string(source)} -> {dot_string(target)} [{attrs}];")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Graphviz DOT graph of SOAC workspace-local crate dependencies."
    )
    parser.add_argument("--out", type=Path, help="Write Graphviz DOT to this path.")
    parser.add_argument(
        "--include-dev",
        action="store_true",
        help="Include dev-dependency edges, styled as dashed edges.",
    )
    args = parser.parse_args()

    output = render_dot(cargo_metadata(), include_dev=args.include_dev)
    if args.out:
        out = args.out if args.out.is_absolute() else ROOT / args.out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(output)
        print(rel(out))
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
