[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "soac"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]
packages = ["soac"]

[tool.setuptools.package-dir]
"" = "src"

[dependency-groups]
dev = [
    "ipython>=9,<10",
    "pytest>=8,<9",
]
