[package]
name = "soac-optimization"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
rkyv = { version = "0.8", features = ["alloc"] }
soac-core = { path = "../soac-core" }
soac-lowering = { path = "../soac-lowering" }
soac-profile = { path = "../soac-profile" }
