[package]
name = "soac-driver"
version = "0.1.0"
edition = "2024"

[lib]
name = "soac_driver"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck"] }
soac-config = { path = "../soac-config" }
soac-core = { path = "../soac-core" }
soac-lowering = { path = "../soac-lowering" }
tracing = "0.1"
