[package]
name = "soac-pyo3"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "_soac_ext"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
soac-lowering = { path = "../soac-lowering" }
soac-driver = { path = "../soac-driver" }
soac-config = { path = "../soac-config" }
soac-core = { path = "../soac-core" }
soac-opt = { path = "../soac-opt" }
soac-jit = { path = "../soac-jit" }
pyo3 = { workspace = true, features = ["extension-module"] }
tracing = "0.1"
serde_json = "1"
rkyv = { version = "0.8", features = ["alloc"] }

[build-dependencies]
build_support = { workspace = true }

[dev-dependencies]
soac-cpython = { path = "../soac-cpython" }
